# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
    - repository: pipeline-plans
      name: pipeline-plans
      type: git
      ref: main

trigger:
  batch: true
  branches:
    include:
    - develop
    - main
    - hotfix/*
  paths:
    exclude:
    - pom.xml

pool:
    name: Azure Pipelines
    demands: maven

variables:
  - group: Anypoint Platform Variable
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: MAVEN_CACHE_FOLDER
    value: $(HOME)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: Test
  displayName: Test Application
  jobs:
  - job: Test
    steps:
      - template: test-mule-app.yml@pipeline-plans
        parameters:
         artifactName: {{ artifact name }}
         env: Dev
    condition: and(succeeded(), eq(variables.isMain, false))

- stage: Build
  displayName: Build Application
  jobs:
  - job: Build
    steps:
      - template: build-mule-app.yml@pipeline-plans
        parameters:
          artifactName: {{ artifact name }}
    condition: and(succeeded(), eq(variables.isMain, false))

- stage: Release
  displayName: Create Release
  jobs:
  - job: Release
    steps:
      - template: create-release-tag.yml@pipeline-plans
        parameters:
         gitUseremail: $BUILD_REQUESTEDFOREMAIL
         gitUsername: "$BUILD_REQUESTEDFOR"
         artifactName: {{ artifact name }}
    condition: and(succeeded(), eq(variables.isMain, true))